### Site info:
title: MoreFreeze
tagline: MoreFreeze's blog
author :
  name : More Freeze
  email : morefreeze@gmail.com
  github : morefreeze
  twitter : morefreeze
email: morefreeze@gmail.com
description: "morefreeze's blog" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, Freshman21"
locale: en_US

### Personal info and site tools info:
favicon:     "/images/favicon.ico"
aboutme: Hi, this is More Freeze. I am a backend engineer in Beijing. I am good at C++, PHP, Python deveploping. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"
      Categories: "分类目录"
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: MoreFreeze
      href: http://morefreeze.github.io
      title: Another Jekyll blog theme

### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
