# Document:
# http://simiki.org/docs/configuration.html

url: 
title: Wiki
keywords: simiki, wiki
description: 
author: MoreFreeze

root: /wiki
source: content
destination: ../wiki
themes_dir: themes
theme: simple

default_ext: md
pygments: true
debug: false
